### ISSUE TITLE
Does not compile on stable

### ISSUE THREAD

**Issue by PhilipDaniels** [regexident/cargo-modules#11]
error[E0554]: #![feature] may not be used on the stable release channel
 --> .cargo\registry\src\github.com-1ecc6299db9ec823\cargo-modules-0.3.5\src\main.rs:1:1
  |
1 | #![feature(rustc_private)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: failed to compile `cargo-modules v0.3.5`

**Comment by regexident** [comment]
Hi Philip,

this is expected behavior as **cargo-modules** is a compiler plugin and thus makes use of unsable features.

Try installing it like this:

```
$ rustup run nightly cargo install cargo-modules
```

Or if you want to build it locally:

```
$ rustup run nightly cargo build --release
```

**Comment by PhilipDaniels** [comment]
Some further observations (did I mention I was trying it on Windows ;-)

I managed to install it by flipping to nightly and the program runs, however if I then flip back using `rustup default stable` then it no longer runs and reports error

    C:/Users/Phil/.cargo/bin/cargo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

If I invoke it directly using `cargo-modules` rather than `cargo modules` I get the error shown in the pic

![cargo_modules_error](https://user-images.githubusercontent.com/1809220/36061658-219c456e-0e55-11e8-958b-ad7d796cfde5.png)

and a whole slew of further similar errors.

I don't expect you to fix this, I just wanted to log it for info. I guess the take-away from this is that you really need to be on nightly to run it, which is a pity.

**Comment by regexident** [comment]
Yeah, same thing applies to usage, unfortunately. I fixed the README.

**cargo-modules** used to work alright with `stable`, but due to [`syntex-syntax`](https://crates.io/crates/syntex_syntax) being deprecated/discontinued I was forced to switch to the [`syntax`](https://github.com/rust-lang/rust/tree/master/src/libsyntax) crate within [rustc](https://github.com/rust-lang/rust). 

Unfortunately rustc's syntax crate is unstable.

I haven't had a chance to look into @dtolnay's [**syn**](https://github.com/dtolnay/syn) crate.  
I'm not sure if **syn** is capable of parsing all of Rust. Maybe @dtolnay can shine some light on it?  
In case it is I could move cargo-modules from syntax to syn, bringing things back to stable rust.

**Comment by dtolnay** [comment]
Yes syn can parse all of Rust.

**Comment by regexident** [comment]
> Yes syn can parse all of Rust.

That's great to know! Thanks for chiming in, @dtolnay!

So, I guess all I need then is a free weekend, or two.
