### ISSUE TITLE
dependencies command panicked: impl type node

### ISSUE THREAD

**Issue by lucasMontenegro** [regexident/cargo-modules#254]
Trying to create a dependency graph for [veloren](https://gitlab.com/veloren/veloren) the command `cargo modules dependencies -p veloren-common --lib` fails with the following message:

```
thread 'main' panicked at src/graph/builder.rs:89:61:
impl type node
```

The same command works fine for other packages, for example: `veloren-common-state`.

I tried cloning the repo but the error still persists.

OS: NixOS 23.11
rust toolchain: 1.74.0

**Comment by regexident** [comment]
Hi @lucasMontenegro, thanks for the report! Would you mind giving https://github.com/regexident/cargo-modules/pull/255 a spin to confirm the fix?

**Comment by lucasMontenegro** [comment]
Hello. It's running but taking its time to complete.

**Comment by lucasMontenegro** [comment]
It's working now. Thank you for the cool project and the quick fix

**Comment by regexident** [comment]
> Hello. It's running but taking its time to complete.

That's because you were probably running it via something along these lines:

```terminal
cargo run -- dependencies <OPTIONS>
```

… which ends up taking a massive hit in performance due to being a debug build. Imagine running a debug-build of `rustc`. 😅

As such I usually do local runs with `--release`:

```terminal
cargo run --release -- dependencies <OPTIONS>
```

> It's working now. Thank you for the cool project and the quick fix

Glad you find it useful! `cargo-modules` tends to have a release per week, so stay tuned for `0.13.4` with this fix (and probably a bumped rust-analyzer) some time later this week. 🙂

**Comment by regexident** [comment]
@lucasMontenegro 0.13.4 was just released, containing the fix.
