### ISSUE TITLE
Feature request: dependencies --no-owns

### ISSUE THREAD

**Issue by wduminy** [regexident/cargo-modules#274]
Thank for for creating this great utility.

A new option `--no-owns` on the `dependencies` command would help me to create a cleaner _usage_ graph.

Looking at the graph below, applying the `--no-owns` option could create a view that shows only the `uses` links.
Perhaps also removing those nodes that do not participate in such a relation.

![out](https://github.com/regexident/cargo-modules/assets/1571851/f4a396c1-d95e-4262-a326-8dc5892e16d9)

**Comment by duckki** [comment]
This seems related to https://github.com/regexident/cargo-modules/issues/265.

**Comment by muhuk** [comment]
This would be quite useful in decipering the graph I get by running the tool on [yer](https://github.com/muhuk/yer)

![image](https://github.com/user-attachments/assets/badf6668-8c1f-49b0-ac7c-c4eeb8bfaae1)

Edges running over nodes are also not helping the situation.

**Comment by muhuk** [comment]
I am specifically looking for circular dependencies like this one between `layer`, `undo` & `session`.

![image](https://github.com/user-attachments/assets/30522d15-2305-4d37-a735-54ade6e7ce21)

**Comment by regexident** [comment]
Would any of you mind giving [this PR](https://github.com/regexident/cargo-modules/issues/274)'s branch a try and report back on whether it addresses your needs?

**Comment by muhuk** [comment]
No! But I'll give #348 a try later today.

**Comment by muhuk** [comment]
Not a very useful output for my codebase. Notice that `session -> undo` and `yer -> undo` arrows are overlapping.

```
cargo modules dependencies --no-externs --no-fns --no-traits --no-types --no-sysroot --no-owns  | dot -Tsvg > mods.svg
```

![image](https://github.com/user-attachments/assets/fae8db4a-0380-4f80-8845-43f6b065a64a)

**Comment by regexident** [comment]
Given that finding an optimal minimally-crossing graph layout (which deals with edge-crossings, but feels related in nature) is known to be NP-complete on arbitrary graphs this issue feels somewhat out-of-scope. 😅

`cargo-modules` merely generates the `.dot` file, while allowing you to pick a different layout algorithm (`--layout "…"`) if so desired. Have you by chance tried that with your graph?

If picking a different layout algorithm doesn't fix the edge-overlap issue, then setting `splines=curved` for the graph itself would be the next thing I'd try:

```dot
digraph {
    graph [
        // ...
        splines="curved"
    ]
    // ...
}
```

I've thought about exposing more graphviz settings (i.e. `shape`, `splines`, …) as CLI options but ended up not doing it due to scope-creep, as well as a fear of flooding the CLI with seldomly used options.

**Comment by muhuk** [comment]
I appreciate this is a dot rendering issue. But I think it's totally possible to create such dependency (`use`) diagrams. C4 (plantuml) does it well [for example](https://github.com/muhuk/grid-uv-packer/blob/master/doc/arch/Component_Diagram.png). (source code for that diagram is [here](https://github.com/muhuk/grid-uv-packer/blob/master/doc/arch/Component_Diagram.plantuml) )

**Comment by wduminy** [comment]
@muhuk Try this to see if it resolves the overlap issue you mention above.

```sh
cargo modules dependencies --no-externs --no-fns --no-traits --no-types --no-sysroot --no-owns  | dot -Gsplines=curved  -Tsvg > mods.svg 
```

**Comment by muhuk** [comment]
@wduminy this is better, but the hierarchy in the architecture is still kind of hidden, because of the haphazard placement of nodes.

![image](https://github.com/user-attachments/assets/3a274d61-953d-4153-a739-ea6051e31dd8)

This time I can clearly see, for example, there are no depenceny cycles with `undo`. But if the # of modules double, and it will, I doubt looking at this graph would be quicker than cheking `use`s within the code.

**Comment by regexident** [comment]
> This time I can clearly see, for example, there are no depenceny cycles with `undo`. But if the # of modules double, and it will, I doubt looking at this graph would be quicker than cheking `use`s within the code.

Yeah, that's unfortunately an inherent problem of network analysis and a lot of research has gone into visual graph navigation over the years, with no clear winners though, imho.

The `--focus-on` and `--max-depth` options can help by being able to put the spotlight on a specific part of the graph, but they certainly are no silver bullet. And I actually haven't tested them against `--no-owns` yet, which filters out "owns" edges after all the other filters have been applied (which made it easier to get something working now, without having to deal with the fiddly edge-cases of structure-preserving graph filtering).

**Comment by muhuk** [comment]
@regexident have you had the chance to look at the graph I shared [here](https://github.com/regexident/cargo-modules/issues/274#issuecomment-2498874206)? Notice all the arrows go from left to right, lower-level modules (that mostly get incoming dependencies) are on the right, higher-level modules (that have more dependencies than incoming dependencies) are on the left.

> Sorting by the "hierarchy" of the architecture is difficult (at least without applying extensive network analysis to derive the most-likely hierarchy from the graph) since the graph isn't a DAG.

But my use case is to figure out if there are circular dependencies. `something::else` is **owned** by `something` is trivial and obvious. I may be wrong but I see no point in having an owns graph. A recursive ls command would show the same info, if needed. But the real value, IMHO, is uses graphs. I want to be able to see [couplings](http://butunclebob.com/ArticleS.UncleBob.ModuleMetricsFixture) between modules.
