### ISSUE TITLE
Not an issue, rather an observation

### ISSUE THREAD

**Issue by 0323pin** [regexident/cargo-modules#329]
It's currently impossible for me to update this package as the requirement seems to be the "latest stable Rust".

This is very nice when the OS only supports x86_64 and bootstraps are provided. On NetBSD, this is only offered for x86_64 which means we need to generate these for the other platforms we support. We aim at having latest -1 but, sometimes, like now we have latest -2. Also, we are keeping 1.76 in tree, that is the last version that builds on ARM 32bits.

So, I'm considering what I should do with a package I've assigned myself as maintainer but, that I can actually not keep up-to-date?

Are these extrem freshness requirements really a must?

Thanks.

**Comment by regexident** [comment]
> Are these extrem freshness requirements really a must?

Unfortunately they are. I'm always making sure to use the lowest possible MSRV for each release, but since `rust-analyzer` (which `cargo-modules` depends on to do the heavy lifting) aims to support the latest available versions of Rust it tends to have to keep up with it, somewhat closely. And thus so do we, transitively.

That said if the users don't have access to the latest Rust versions in the first place, then they very likely won't be missing out much for `cargo-modules` either, as most features in `cargo-module` have matured by now, bug-fixed have become more and more rare and (as evident from the CHANGELOG) we're mostly doing (semi-)weekly releases to keep up with `rust-analyzer` at this point.

**Comment by 0323pin** [comment]
@regexident Fair enough. Yes, I have noticed from the release notes that most releases are dependency bumps which, I guessed means _mostly feature complete_.

I should be able to push 0.17.x rather soon but, 0.18.x will have to wait. Yes, users can use the software a few versions behind. I just have to deal with a bit of red in my Repology page.

Think, I'll close this non-issue now.
