### ISSUE TITLE
Doesn't understand cfg-if

### ISSUE THREAD

**Issue by asomers** [regexident/cargo-modules#41]
Cargo-modules tries to show the full dependency graph including all conditional dependencies.  However, it doesn't understand the popular `cfg-if` macro, leading to missing dependencies.  As an example, create a crate with four empty files: src/{foo, bar, baz, bean}.rs, and main.rs having the following content:
```rust
use cfg_if::cfg_if;

cfg_if! {
    if #[cfg(test)] {
        pub use self::foo;
    } else {
        pub use self::bar;
    }
}

#[cfg(test)]
pub use self::baz;

#[cfg(not(test))]
pub use self::bean;
```
cargo-modules gives the following output:
```
digraph {
    label="cmci";
    pad=0.4;

    // Modules
    "cmci" [label="cmci", color=green4, fontcolor=green4 style=filled, fillcolor=greenyellow]

    // Hierarchy
    "cmci" -> "cmci::bar" [weight=50, color=firebrick4, penwidth=1]
    "cmci" -> "cmci::foo" [weight=50, color=firebrick4, penwidth=1]
    "cmci" -> "cmci::baz" [weight=50, color=firebrick4, penwidth=1]
    "cmci" -> "cmci::bean" [weight=50, color=firebrick4, penwidth=1]

    // Dependencies
    "cmci" -> "cmci::baz" [weight=90, color=azure3, penwidth=2, label=<<FONT POINT-SIZE="10" COLOR="azure3">use <B>self</B></FONT>>]
    "cmci" -> "cmci::bean" [weight=90, color=azure3, penwidth=2, label=<<FONT POINT-SIZE="10" COLOR="azure3">use <B>self</B></FONT>>]
}
```

Notice that the cmci->cmci::foo and cmci->cmci::bar dependencies are missing.

**Comment by wycats** [comment]
Why doesn't `cargo-modules` expand macros before building the graph?

**Comment by regexident** [comment]
@wycats historically speaking because I back then tried to avoid adding too many moving parts, given that I already had to frequently fix breakage due to unstable `syntex_syntax` dependency.

There is no reason why it should _not_ expand macros now. I'm wondering though if it wouldn't then make more sense to go all in, turn **cargo-modules** into a `rustc_driver` walk the HIR instead, which should get us the [name resolution](https://rust-lang.github.io/rustc-guide/name-resolution.html) for free. Something that @muhuk has been [doing tremendous manual work](https://github.com/regexident/cargo-modules/issues/34) recently, in an effort to add support for Edition 2018.

**Comment by muhuk** [comment]
...and he still needs to do some more work, to finalize it.

Soon I'll get to it.

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
