### ISSUE TITLE
Can't find tag for version 0.4.10 from crates.io

### ISSUE THREAD

**Issue by soenkehahn** [regexident/cargo-modules#75]
The `cargo-modules` version on crates.io is `0.4.10` (see [here](https://crates.io/crates/cargo-modules)). However I can't find a corresponding tag for that version in this repo. Which commit was uploaded to crates.io as `0.4.10`? Thanks!

**Comment by regexident** [comment]
That's because I forgot ti create it 😇.
Thanks for catching it, here it is: [0.4.10](https://github.com/regexident/cargo-modules/releases/tag/0.4.10).

<sub>Be advised however that you might want to migrate to the latest beta of `0.5`, as versions `<0.5` tend to break whenever the `rustc` changes (with `0.5` the project moved to `rust-analyzer` which isn't stable either, but at least I can update it selectively).</sub>

**Comment by soenkehahn** [comment]
Thanks a lot!
