### ISSUE TITLE
Option to disable module nodes in graph

### ISSUE THREAD

**Issue by kangalio** [regexident/cargo-modules#98]
I'd love to use cargo modules as a tool to optimize my project's module structure. When rendering items and their interdependencies, the output looks very messy:
![image](https://user-images.githubusercontent.com/21220820/147259355-27c633c0-672e-4709-9f98-afd1065a0cec.png)

If it were possible to disable modules nodes, this graph would look significantly cleaner but still contain the information about item interdependencies.

**Comment by regexident** [comment]
Hi @kangalioo,

I too would love to be able to generate a pure type-dependencies graph, but unfortunately afaiui `rust-analyzer` (which powers `cargo-modules`) only provides dependency information on module scope. It's possible that I either missed something when I last looked at the APIs provided by `rust-analyzer` or that it has since gained support for type-level dependencies.

**Comment by kangalioo** [comment]
> It's possible that I either missed something when I last looked at the APIs provided by rust-analyzer or that it has since gained support for type-level dependencies.

Which crate would I need to look at to double-check? [ra_ap_hir](https://docs.rs/ra_ap_hir)?

**Comment by regexident** [comment]
Either that or `ra_ap_ide_db` in my experience. But then again I might have searched in the wrong corners and with the wrong keywords.

**Comment by regexident** [comment]
@kangalio The just released version `0.8.0` provides a `--no-modules` CLI argument for filtering out modules from graphs.
